### ISSUE TITLE
Masking can be faster by operating on bigger chunks at a time

### ISSUE THREAD

**Issue by bluetech** [methane/wsaccel#17]
The `XorMasker` loop does its work a byte at a time.

```
for i in range(dlen):
    out[i] = cdata[i] ^ self.mask[self.ptr & 3]
    self.ptr += 1
```

It can be made much faster by doing the masking 4 bytes at a time. Another option is 8 bytes at a time for 64bit machines, but this is not worth it from my tests.

Any implementation of this would have to worry about alignment. This complicates the code, and slows it down a bit, but only by a fixed factor.

Here is a quick comparison of the approaches I wrote in C. Please note that this does *not* handle misaligned input: https://gist.github.com/bluetech/36ac1d0b21864a4f42fa723de569e5f8

Results compiled with `gcc -O3 -march=native mask.c -o mask` (best out of 3):

```
8 by 8:   4420646
32 by 32: 711165
64 by 64: 524392
```

With `clang -O3 -march=native mask.c -o mask` (best out of 3):

```
8 by 8:   2041846
32 by 32: 265903
64 by 64: 265590
```

So for the bare loop itself, it's a 5x - 10x improvement.

**Comment by methane** [comment]
Is it worth enough for real websocket workload?

**Comment by bluetech** [comment]
Depends on what you consider a real workload. A websocket implementation spends a lot of its time doing masking (well, maybe not one written in Python). I suspect the reason why most projects depend on wsaccel is to get faster masking. If this can be done 5x faster, I think it's worth it.

**Comment by methane** [comment]
Could you try this file?
https://github.com/methane/wsaccel/blob/master/bench/bench.py

**Comment by methane** [comment]
Say pure Python masking takes 50% of application CPU time and wsaccel make it 100x faster,
wsaccel boost the application almost 2x and masking takes only 1% of CPU.

Then, making mask more 5x faster, 1% goes 0.2%.  But application performance is not changed significantly.

Simplest websocket application is echo.
If performance of echo server written with autobahn or ws4py is significantly boosted, it's worth enough.

**Comment by bluetech** [comment]
I tried all 3 benchmarks - `bench.py`, `bench_tornado.py`, `bench_gevent.py` - but failed to get any of them to run without errors. They all seem to be using very old versions of their corresponding dependencies, there is no `requirements.txt` to lock them, and the latest versions don't work.

**Comment by methane** [comment]
Tornado is deprecated because it has own speedup module already.
I updated autobahn bench.

**Comment by methane** [comment]
And I removed bench_gevent.

**Comment by bluetech** [comment]
Thanks, I can run it now. But before any meaningful changes, I'd like to propose the following:

1. Increase the benchmark's iteration count, it's a bit too low now, finishing in 0.15s. Maybe it's enough for profiling, I don't know, but starting the interpreter must have some overhead.

2. Increase the message size. It is currently 1000 which is quite low. I mean, it depends on what you intend to achieve:
    - Create realistic "real world" benchmark, in which case 1000 may be representative (still too low IMO, but can go either way).
    - Benchmark the actual library routines (UTF-8 validation and masking), in which case it is way too low, completely drowned by Python overhead.

3. Apply the following diff, which already cuts the masking time by half, from my profile:

```.diff
diff --git a/wsaccel/xormask.pyx b/wsaccel/xormask.pyx
index b89cc82..7e66f4d 100644
--- a/wsaccel/xormask.pyx
+++ b/wsaccel/xormask.pyx
@@ -59,7 +59,7 @@ cdef class XorMaskerSimple:
 
         for i in range(dlen):
             out[i] = cdata[i] ^ self.mask[self.ptr & 3]
-            self.ptr += 1
+        self.ptr += dlen
```

For some reason the compiler does not hoist it out of the loop itself (`self.ptr` is signed, hence overflow is undefined for it, hence the compiler is allowed to hoist it, IIUC). I don't want to "cheat" by pulling that in with my proposed change.

**Comment by bluetech** [comment]
Oh, I noticed the compiler is passed `-fwrapv`, making signed overflow defined and disabling the optimization, probably. I assume Cython does it on its own.

**Comment by methane** [comment]
> Increase the benchmark's iteration count, it's a bit too low now, finishing in 0.15s. Maybe it's enough for profiling, I don't know, but starting the interpreter must have some overhead.

OK.  But the time doesn't include interpreter startup already.

> Increase the message size. It is currently 1000 which is quite low. I mean, it depends on what you intend to achieve:

I think 1000 is realistic  rather than "quite low".  But OK to use 100K instead.

> Benchmark the actual library routines (UTF-8 validation and masking), in which case it is way too low, completely drowned by Python overhead.

OK for adding new microbench.
But don't remove macro bench.  I feel "worth enough" only when there is meaningful speedup on macro bench.

> Apply the following diff, which already cuts the masking time by half, from my profile:

OK.  It seems very simple.  I will accept it if you send pull request.

**Comment by dsuch** [comment]
Hello,

as requested by @methane, I am leaving a note whether this kind of improvements is visible in macro-benchmarks.

The answer is yes, this is visible under a profiler in real-world workloads.

If you have a system where 1kB is considered an average size then then the system's total processing time will be possibly dominated by other factors.

But if you typically exchange messages that are 32-64-256-1024 or more kilobytes in size then masking alone will constitute at least 5%-10% of everything happening on server side. Since this is a pure CPU activity, GIL becomes a factor too.

This is a real shame because, as I am writing it in 2021, there is no practical value in masking at all given that it guards against an attack that is completely unrealistic now with TLS everywhere. But here we are, with an RFC which says that masking MUST be used.

That aside, please understand that WebSocket connections are used not only by web browsers or server-to-server communication.

Another area are IoT integrations with small devices where 64 MB of RAM may be already a lot - every millisecond counts a lot in such circumstances and making sure that the server has as little overhead as possible becomes even more important.

Thus, to sum it up, yes, processing N bytes in a single iteration of the masking's main loop definitely makes sense and will positively influence real-world benchmarks.

Thanks.

**Comment by methane** [comment]
Why do you use wsaccel? Autobahn and ws4py are not maintained actively, so I don't have motivation to improve this project too.

If you want to faster masker, you can use Tornado. Tornado provides `websocket_mask()` function.
https://github.com/tornadoweb/tornado/blob/master/tornado/speedups.c

So you can use it for `Frame.mask()` and `Frame.unmask()`.

**Comment by dsuch** [comment]
I did not realise that this project was not to be used - its description says that it provides certain features, the last commit is from December 2020 and there is nothing to make one understand that one should use something else.

I understand it now and I suggest to add the relevant notes to GitHub's readme and to PyPI. Otherwise, I genuinely thought this was an actively maintained project offering particular features that I needed.

**Comment by methane** [comment]
I actively maintains this project to keep working. I just won't improve it.
